NAME RteMethParms
  RTEINTPARMS 1, 5, 100, 1, 0.2, 0, 5, 100, 0, 0, 1, 0
  RETURN

NAME LoadMiscParams
  LOCAL a$,b$,c$,d$
  a$="D:\MassHunter\Library\NIST14.L"
  b$="D:\MassHunter\Library\NIST08.L"
  c$=""
  d$=""
  QUALRPTOPT 0,1,0,1,"NORMA  LIBRARY EFVS",0
  QUALPARMS a$,b$,c$,0.000000,0.000000,1,0.000000,0,d$
  PCTRPTOPT 0,1,0,1,"NORMA PERCENT",0,0,""
  SPECTRAL_WINDOW = 0.200100
  PCTSCWIN = 0.020000
  MZRANGE = -0.300000:0.700000
  RteMethParms
  RETURN
